### ISSUE TITLE
Comment field bug: first 3 chars removed

### ISSUE THREAD

**Issue by coins-black** [broxus/wallet-desktop#1] opened 2020-12-23 16:17 UTC
Hi!

When specifying the Comment field in a transaction to send funds, the first 3 characters of the comment are removed. The bug may not show up if the comment is less than 6 characters long.

Mechanics of the bug:
1. you specify a comment for the transaction
2. if you look through the history of transactions in the wallet itself, the comment is always correct there
3. if you look up this transaction already in the explorer, you will find that the first 3 characters are missing in the comment body

**Comment by Rexagon** [comment] 2020-12-24 09:31
Hi, thanks for reporting this.

I think the problem is how these message payloads were formed and parsed. Message comments in this app were made more then half a year ago, before Surf and etc, so it packs them differently. If the recipient watched transactions through the same application, he would see them in full.

Maybe it is a time to somehow migrate to the new comments payload format, which is used by tonlabs. I'll implement it next week.

**Comment by coins-black** [comment] 2020-12-24 11:16
Thanks for reply.The main problem is that exchanges (like Kuna and exchange.bitcoin.com) use comment (memo) to deposit account balance and their API saw payload without first 3 chars. So funds hasn't been credited to account12:31, 24 декабря 2020 г., Ivan Kalinin <notifications@github.com>:
Hi, thanks for reporting this.
I think the problem is how these message payloads were formed and parsed. Message comments in this app were made more then half a year ago, before Surf and etc, so it packs them differently. If the recipient watched transactions through the same application, he would see them in full.
Maybe it is a time to somehow migrate to the new comments payload format, which is used by tonlabs. I'll implement it next week.

**Comment by Rexagon** [comment] 2020-12-25 14:38
Fixed in 1.1.3, please update on windows. Thank you!

**Closed as completed by Rexagon** 2020-12-25 14:38 UTC
Labels: enhancement

**Comment by coins-black** [comment] 2020-12-25 20:25
Thanks 👍17:39, 25 декабря 2020 г., Ivan Kalinin <notifications@github.com>:
Fixed in 1.1.3, please update on windows. Thank you!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
